# Generated by Django 4.0.3 on 2023-04-01 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('node_api', '0010_alter_notemodel_currenttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('completed', models.FloatField(blank=True, default=0, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Certificate',
                'ordering': ['-createdAt'],
            },
        ),
    ]
